import { AuthProvider } from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
// import Navbar from "@/components/Navbar";
// import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const router = useRouter();
  // const hideNavbar = router.pathname === '/dashboard';
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        {/* {!hideNavbar && <Navbar />} */}
        
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
